import type { InkIconKey, InkPremiumFeature, InkThemeTokens } from '../types';

export const INK_PREMIUM_LICENSE_PREFIX = 'ink_prem_';

export const INK_PREMIUM_FEATURES: InkPremiumFeature[] = [
  'icons',
  'theme',
  'richPaste',
  'imageUpload',
  'wysiwyg',
];

export const INK_DEFAULT_ICONS: Record<InkIconKey, string> = {
  bold: 'B',
  italic: 'I',
  underline: 'U',
  strikethrough: 'S',
  bulletList: '•',
  orderedList: '1.',
  link: '🔗',
  image: '🖼',
  table: '▦',
  signature: '✍',
  findReplace: '⌕',
  undo: '↶',
  redo: '↷',
  trackChanges: '±',
  comments: '💬',
  ai: '✦',
  clearFormat: '⌫',
  alignLeft: '⫷',
  alignCenter: '☰',
  alignRight: '⫸',
  alignJustify: '≡',
  indent: '→',
  outdent: '←',
  blockquote: '“',
  code: '</>',
};

export const INK_THEME_CSS_VARS: Record<keyof InkThemeTokens, string> = {
  border: '--ink-border',
  background: '--ink-bg',
  toolbar: '--ink-toolbar',
  text: '--ink-text',
  muted: '--ink-muted',
  accent: '--ink-accent',
  accentSoft: '--ink-accent-soft',
  shadow: '--ink-shadow',
  radius: '--ink-radius',
  fontFamily: '--ink-font-family',
};

export const INK_PASTE_ALLOWED_TAGS = [
  'p',
  'br',
  'div',
  'span',
  'strong',
  'b',
  'em',
  'i',
  'u',
  's',
  'strike',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'ul',
  'ol',
  'li',
  'blockquote',
  'pre',
  'code',
  'a',
  'img',
  'table',
  'thead',
  'tbody',
  'tr',
  'th',
  'td',
  'hr',
  'sub',
  'sup',
] as const;

export const INK_PASTE_ALLOWED_ATTRS = [
  'href',
  'src',
  'alt',
  'title',
  'style',
  'colspan',
  'rowspan',
  'width',
  'height',
  'target',
  'rel',
] as const;
