import { NUMBER_TWO, NUMBER_FOUR, NUMBER_SIX, NUMBER_TWO_HUNDRED_FIFTY, NUMBER_TWO_HUNDRED_FIFTY_FIVE } from '@/constants/numbers';

export const SIGN_PAD_CLASS = 'Ink-SignPad flex flex-col gap-2 p-3 border-b';
export const SIGN_PAD_CANVAS_CLASS = 'Ink-SignPad__canvas w-full max-w-xl h-44 border border-dashed rounded-lg bg-white cursor-crosshair';
export const SIGN_PAD_ACTIONS_CLASS = 'Ink-SignPad__actions flex flex-wrap gap-1';
export const SIGN_PAD_TITLE_CLASS = 'Ink-SignPad__title m-0 text-sm font-semibold';
export const SIGN_PAD_DEFAULT_TITLE = 'Sign here';
export const SIGN_PAD_DEFAULT_CLEAR = 'Clear';
export const SIGN_PAD_DEFAULT_CONFIRM = 'Insert';
export const SIGN_PAD_DEFAULT_CANCEL = 'Cancel';
export const SIGN_PAD_CANVAS_WIDTH = 480;
export const SIGN_PAD_CANVAS_HEIGHT = 180;
export const SIGN_PAD_LINE_WIDTH = NUMBER_TWO;
export const SIGN_PAD_STROKE_STYLE = '#111827';
export const SIGN_PAD_FILL_STYLE = '#ffffff';
export const SIGN_PAD_MIME = 'image/png';
export const SIGN_PAD_EMPTY_ALPHA_THRESHOLD = NUMBER_FOUR;
export const SIGN_PAD_SAMPLE_STEP = NUMBER_SIX;
export const SIGN_PAD_FILL_CHANNEL = NUMBER_TWO_HUNDRED_FIFTY_FIVE;
export const SIGN_PAD_INK_CHANNEL_MAX = NUMBER_TWO_HUNDRED_FIFTY;
export const SIGN_PAD_RGBA_STRIDE = NUMBER_FOUR;
export const SIGN_PAD_RED_OFFSET = 0;
export const SIGN_PAD_GREEN_OFFSET = 1;
export const SIGN_PAD_BLUE_OFFSET = 2;
export const SIGN_PAD_ALPHA_OFFSET = 3;
