import { NUMBER_TWENTY_EIGHT, NUMBER_FOURTEEN, NUMBER_TWELVE, NUMBER_SIXTEEN, NUMBER_TWENTY_FOUR } from '@const/numbers';

export const REMOTE_CURSOR_LINE_HEIGHT_PX = NUMBER_TWENTY_EIGHT;
export const REMOTE_CURSOR_TOP_OFFSET_PX = NUMBER_FOURTEEN;
export const REMOTE_CURSOR_MIN_TOP_PX = NUMBER_TWELVE;
export const REMOTE_CURSOR_CHAR_WIDTH_PX = 8.5;
export const REMOTE_CURSOR_LEFT_OFFSET_PX = NUMBER_TWENTY_FOUR;
export const REMOTE_CURSOR_MIN_LEFT_PX = NUMBER_SIXTEEN;
